apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securetimeauthorities.uml001.io
spec:
  group: uml001.io
  names:
    kind: SecureTimeAuthority
    plural: securetimeauthorities
    singular: securetimeauthority
    shortNames:
      - sta
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - quorum
                - crypto
              properties:
                quorum:
                  type: object
                  properties:
                    minQuorum:
                      type: integer
                    maxClusterSkew:
                      type: integer
                    failClosed:
                      type: boolean
                crypto:
                  type: object
                  required:
                    - mode
                  properties:
                    mode:
                      type: string
                      enum:
                        - HMAC
                        - ED25519
                        - TPM_SEALED_ED25519
                    rotationIntervalSeconds:
                      type: integer
                    overlapWindowSeconds:
                      type: integer
                tpm:
                  type: object
                  properties:
                    enableRemoteAttestation:
                      type: boolean
                    keyLabel:
                      type: string
                exposure:
                  type: object
                  properties:
                    serviceType:
                      type: string
                      enum:
                        - ClusterIP
                        - LoadBalancer
                        - NodePort