apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securetimepolicies.uml001.io
spec:
  group: uml001.io
  names:
    kind: SecureTimePolicy
    plural: securetimepolicies
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                requireTPM:
                  type: boolean
                requireAttestation:
                  type: boolean
                allowedCryptoModes:
                  type: array
                  items:
                    type: string