# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bridge_pb2 as bridge__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeTimeServiceStub(object):
    """-------------------------------------------------------------------------
    BridgeTimeService

    Consumer-facing gRPC API for the Aegis bridge.  This is intentionally
    separate from the internal clock_service.proto so downstream clients
    are not coupled to the BFT daemon internals.
    -------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/aegisbridge.BridgeTimeService/GetTime',
                request_serializer=bridge__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=bridge__pb2.TimeResponse.FromString,
                _registered_method=True)
        self.GetTimeAttested = channel.unary_unary(
                '/aegisbridge.BridgeTimeService/GetTimeAttested',
                request_serializer=bridge__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=bridge__pb2.AttestedTimeResponse.FromString,
                _registered_method=True)


class BridgeTimeServiceServicer(object):
    """-------------------------------------------------------------------------
    BridgeTimeService

    Consumer-facing gRPC API for the Aegis bridge.  This is intentionally
    separate from the internal clock_service.proto so downstream clients
    are not coupled to the BFT daemon internals.
    -------------------------------------------------------------------------

    """

    def GetTime(self, request, context):
        """GetTime returns a compact timestamp response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeAttested(self, request, context):
        """GetTimeAttested returns the full quorum attestation envelope.
        Use this when the consumer needs to carry the quorum proof through
        their own audit trail or verify the result independently.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeTimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=bridge__pb2.GetTimeRequest.FromString,
                    response_serializer=bridge__pb2.TimeResponse.SerializeToString,
            ),
            'GetTimeAttested': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeAttested,
                    request_deserializer=bridge__pb2.GetTimeRequest.FromString,
                    response_serializer=bridge__pb2.AttestedTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegisbridge.BridgeTimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegisbridge.BridgeTimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BridgeTimeService(object):
    """-------------------------------------------------------------------------
    BridgeTimeService

    Consumer-facing gRPC API for the Aegis bridge.  This is intentionally
    separate from the internal clock_service.proto so downstream clients
    are not coupled to the BFT daemon internals.
    -------------------------------------------------------------------------

    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegisbridge.BridgeTimeService/GetTime',
            bridge__pb2.GetTimeRequest.SerializeToString,
            bridge__pb2.TimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeAttested(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegisbridge.BridgeTimeService/GetTimeAttested',
            bridge__pb2.GetTimeRequest.SerializeToString,
            bridge__pb2.AttestedTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
