# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x0b\x61\x65gisbridge\"\x10\n\x0eGetTimeRequest\"a\n\x0cTimeResponse\x12\x14\n\x0cunix_seconds\x18\x01 \x01(\x03\x12\x12\n\nunix_nanos\x18\x02 \x01(\x03\x12\x0f\n\x07iso8601\x18\x03 \x01(\t\x12\x16\n\x0euncertainty_ms\x18\x04 \x01(\x01\"\xc5\x01\n\x14\x41ttestedTimeResponse\x12\x14\n\x0cunix_seconds\x18\x01 \x01(\x03\x12\x12\n\nunix_nanos\x18\x02 \x01(\x03\x12\x0f\n\x07iso8601\x18\x03 \x01(\t\x12\x16\n\x0euncertainty_ms\x18\x04 \x01(\x01\x12\x11\n\tdrift_ppm\x18\x05 \x01(\x01\x12\x18\n\x10\x61\x63\x63\x65pted_sources\x18\x06 \x03(\t\x12\x18\n\x10rejected_sources\x18\x07 \x03(\t\x12\x13\n\x0bquorum_hash\x18\x08 \x01(\t2\xa9\x01\n\x11\x42ridgeTimeService\x12\x41\n\x07GetTime\x12\x1b.aegisbridge.GetTimeRequest\x1a\x19.aegisbridge.TimeResponse\x12Q\n\x0fGetTimeAttested\x12\x1b.aegisbridge.GetTimeRequest\x1a!.aegisbridge.AttestedTimeResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_GETTIMEREQUEST']._serialized_start=29
  _globals['_GETTIMEREQUEST']._serialized_end=45
  _globals['_TIMERESPONSE']._serialized_start=47
  _globals['_TIMERESPONSE']._serialized_end=144
  _globals['_ATTESTEDTIMERESPONSE']._serialized_start=147
  _globals['_ATTESTEDTIMERESPONSE']._serialized_end=344
  _globals['_BRIDGETIMESERVICE']._serialized_start=347
  _globals['_BRIDGETIMESERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
